/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedUnitsRouteImport } from './routes/_protected/units'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedInvitationsCreateRouteImport } from './routes/_protected/invitations/create'
import { Route as AuthInvitationsAcceptRouteImport } from './routes/_auth/invitations/accept'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUnitsRoute = ProtectedUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedInvitationsCreateRoute =
  ProtectedInvitationsCreateRouteImport.update({
    id: '/invitations/create',
    path: '/invitations/create',
    getParentRoute: () => ProtectedRoute,
  } as any)
const AuthInvitationsAcceptRoute = AuthInvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof AuthLoginRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/units': typeof ProtectedUnitsRoute
  '/invitations/accept': typeof AuthInvitationsAcceptRoute
  '/invitations/create': typeof ProtectedInvitationsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/login': typeof AuthLoginRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/units': typeof ProtectedUnitsRoute
  '/invitations/accept': typeof AuthInvitationsAcceptRoute
  '/invitations/create': typeof ProtectedInvitationsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/units': typeof ProtectedUnitsRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_auth/invitations/accept': typeof AuthInvitationsAcceptRoute
  '/_protected/invitations/create': typeof ProtectedInvitationsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/units'
    | '/invitations/accept'
    | '/invitations/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/units'
    | '/invitations/accept'
    | '/invitations/create'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_auth/login'
    | '/_protected/dashboard'
    | '/_protected/units'
    | '/_protected/'
    | '/_auth/invitations/accept'
    | '/_protected/invitations/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/units': {
      id: '/_protected/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof ProtectedUnitsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/invitations/create': {
      id: '/_protected/invitations/create'
      path: '/invitations/create'
      fullPath: '/invitations/create'
      preLoaderRoute: typeof ProtectedInvitationsCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/invitations/accept': {
      id: '/_auth/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof AuthInvitationsAcceptRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthInvitationsAcceptRoute: typeof AuthInvitationsAcceptRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthInvitationsAcceptRoute: AuthInvitationsAcceptRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedUnitsRoute: typeof ProtectedUnitsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedInvitationsCreateRoute: typeof ProtectedInvitationsCreateRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedUnitsRoute: ProtectedUnitsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedInvitationsCreateRoute: ProtectedInvitationsCreateRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
